import type { Metadata } from "next";
import { Roboto,Space_Grotesk} from "next/font/google";
import "./globals.css";
import { Children } from "../type";
import { ThemeProvider } from "@/components/provoider/themeprovoider";



const roboto = Roboto({
  weight:['300','400','500','600','700','800','900',],
  variable:'--font-roboto-sans',
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  weight:['500','600'],
  variable: "--font-spaceGrotesk-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children} :Children ) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${spaceGrotesk.variable} antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
